server:
  port: 9090
spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blitzbuy?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
    #database connection pool
    hikari:
      pool-name: Blitzbuy_Hikari_Pool
      minimum-idle: 5
      idle-timeout: 60000
      max-lifetime: 180000
      connection-timeout: 30000
      connection-test-query: select 1
      maximum-pool-size: 10
      auto-commit: true
  data:
    redis:
#      virtual machine IP
      host: 192.168.33.10
      port: 6379
      database: 0
      timeout: 10000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: 10000ms
          max-idle: 200
          min-idle: 5
      password: foobared
  # RabbitMQ configuration
  rabbitmq:
    host: 192.168.33.10  # Use your virtual machine IP
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    # Connection pool configuration
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
        prefetch: 1
        auto-startup: true
        default-requeue-rejected: true
    template:
      retry:
        enabled: true
        initial-interval: 1000ms
        max-attempts: 3
        max-interval: 10000ms
        multiplier: 1.0
        max-interval: 10000ms


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.example.blitzbuy.pojo


logging:
  level:
    root: info
    org.springframework.jdbc: debug  # JDBC underlying logs
    org.mybatis: debug
    com.baomidou.mybatisplus: trace # MyBatis-Plus full logs
    com.example.blitzbuy.mapper: trace
    java.sql: debug                 # Show JDBC connection details
    java.sql.Statement: debug
    java.sql.PreparedStatement: debug