server:
  port: 9090
spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blitzbuy?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
    #database connection pool
    hikari:
      pool-name: Blitzbuy_Hikari_Pool
      minimum-idle: 5
      idle-timeout: 60000
      max-lifetime: 180000
      connection-timeout: 30000
      connection-test-query: select 1
      maximum-pool-size: 10
      auto-commit: true
  data:
    redis:
      host: 192.168.33.10
      port: 6379
      database: 0
      timeout: 10000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: 10000ms
          max-idle: 200
          min-idle: 5
      password: foobared



mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.example.blitzbuy.pojo

logging:
  level:
    com.example.blitzbuy.mapper: debug
#    org.springframework: DEBUG
#    org.mybatis: DEBUG